-- Your SQL goes here
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    first_name CHARACTER VARYING(150) NOT NULL,
    last_name CHARACTER VARYING(150) NOT NULL,
    email CHARACTER VARYING(150) UNIQUE NOT NULL,
    password CHARACTER VARYING(150) NOT NULL,
    strikes INTEGER DEFAULT 0 NOT NULL,
    loan_limit INTEGER DEFAULT 15000 NOT NULL,
    goodwill INTEGER DEFAULT 0 NOT NULL,
    loans_taken INTEGER DEFAULT 0 NOT NULL,
    successful_returns INTEGER DEFAULT 0 NOT NULL,
    default_times INTEGER DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
)